{'roteiro': 
  {'atenas': 'iste 3 pontos turísticos da cidade de Atenas e para cada um deles informe o número anual de visitantes e uma breve descrição', 
  'roma': 'liste 3 pontos turísticos da cidade de Roma e para cada um deles informe o número anual de visitantes e uma breve descrição'}
}